### ISSUE TITLE
요청 : 각 주제를 정리한 마크다운 문서 이름 변경

### ISSUE THREAD

**Issue by ghost** [FEhyoeun/design-patterns#2]
정리해주신 내용 잘 읽었어요! 😃 
혹시 `singleton.md` 파일 이름을 `readme.md` 로 변경해주실 수 있으실까요?
readme.. 로 해주신다면 Singleton 폴더로 들어오면 해당 마크다운 파일이 바로 보여질거에요!

**Comment by FEhyoeun** [comment]
헉 그렇군요.
말씀해주신 것처럼 마크다운 파일명을 변경하겠습니다. 좋은 정보 알려주셔서 감사해요!!! 🙇‍♀️🙇‍♀️❤️

**Comment by FEhyoeun** [comment]
파일명 변경 완료하여 이슈 종료하겠습니당. 감사합니다!!!
